//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBOX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ProductoId { get; set; }
        public Nullable<int> SubcategoriaId { get; set; }
        public Nullable<int> MarcaId { get; set; }
        public string nomProducto { get; set; }
        public string Foto { get; set; }
        public Nullable<float> Precio { get; set; }
    }
}
